"""20240928_migration2

Revision ID: 3056343e76ed
Revises: e3dda32ac0e4
Create Date: 2024-09-28 13:52:30.636482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3056343e76ed'
down_revision = 'e3dda32ac0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibit_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money_currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'money_currency', ['money_currency_id'], ['money_currency_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibit_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('money_currency_id')

    # ### end Alembic commands ###
