"""20240928_migration

Revision ID: 6d6794ef188a
Revises: 
Create Date: 2024-09-27 15:37:52.015928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6794ef188a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('exhibit_info',
    sa.Column('exhibit_info_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_display_name', sa.String(length=256), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('current_exhibit_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('exhibit_info_id')
    )
    op.create_table('money_currency',
    sa.Column('money_currency_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('money_currency_id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('storage_space',
    sa.Column('storage_space_id', sa.Integer(), nullable=False),
    sa.Column('storage_space_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('storage_space_id')
    )
    op.create_table('work',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('work_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_table('character',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=256), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['work.work_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('exhibitor_platform',
    sa.Column('exhibitor_platform_id', sa.Integer(), nullable=False),
    sa.Column('exhibitor_platform_name', sa.String(length=128), nullable=False),
    sa.Column('money_currency_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['money_currency_id'], ['money_currency.money_currency_id'], ),
    sa.PrimaryKeyConstraint('exhibitor_platform_id')
    )
    op.create_table('japan',
    sa.Column('prefecture_id', sa.Integer(), nullable=False),
    sa.Column('prefecture_name', sa.String(length=128), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.PrimaryKeyConstraint('prefecture_id')
    )
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_name', sa.String(length=128), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('world',
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=128), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.PrimaryKeyConstraint('world_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('trade_name', sa.String(length=128), nullable=True),
    sa.Column('purchaser_name', sa.String(length=128), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('japan_id', sa.Integer(), nullable=True),
    sa.Column('exhibitor_platform_id', sa.Integer(), nullable=False),
    sa.Column('now_location', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.ForeignKeyConstraint(['exhibitor_platform_id'], ['exhibitor_platform.exhibitor_platform_id'], ),
    sa.ForeignKeyConstraint(['japan_id'], ['japan.prefecture_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.status_id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['world.world_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('total_exhibit_quantity', sa.Integer(), nullable=True),
    sa.Column('exhibitor_platform_id', sa.Integer(), nullable=True),
    sa.Column('storage_space_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['exhibitor_platform_id'], ['exhibitor_platform.exhibitor_platform_id'], ),
    sa.ForeignKeyConstraint(['storage_space_id'], ['storage_space.storage_space_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.work_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('exhibit_product',
    sa.Column('exhibit_product_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_info_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibit_info_id'], ['exhibit_info.exhibit_info_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('exhibit_product_id')
    )
    op.create_table('order_detail',
    sa.Column('order_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.create_table('photo',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('product_tag',
    sa.Column('product_tag_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_tag_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('product_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_tag')
    op.drop_table('photo')
    op.drop_table('order_detail')
    op.drop_table('exhibit_product')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('world')
    op.drop_table('shipment')
    op.drop_table('japan')
    op.drop_table('exhibitor_platform')
    op.drop_table('character')
    op.drop_table('work')
    op.drop_table('storage_space')
    op.drop_table('status')
    op.drop_table('money_currency')
    op.drop_table('exhibit_info')
    op.drop_table('category')
    op.drop_table('area')
    # ### end Alembic commands ###
