"""20240928_migration

Revision ID: e3dda32ac0e4
Revises: 6d6794ef188a
Create Date: 2024-09-28 13:32:19.347002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dda32ac0e4'
down_revision = '6d6794ef188a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibit_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exhibitor_platform_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'exhibitor_platform', ['exhibitor_platform_id'], ['exhibitor_platform_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibit_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exhibitor_platform_id')

    # ### end Alembic commands ###
